DROP TABLE IF EXISTS COMPRADOR;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS CIDADE;
DROP TABLE IF EXISTS ENDERECO;

CREATE TABLE COMPRADOR (ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255),
    ENDERECOS VARCHAR (255));

    INSERT INTO COMPRADOR (NOME, ENDERECOS) VALUES ('Pedre', 'rua x 2');


CREATE TABLE PEDIDO (ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COMPRADOR1 VARCHAR (255),
    HORARIO VARCHAR(255),
    ITENS INT);


    INSERT INTO PEDIDO (COMPRADOR, HORARIO, ITENS) VALUES ('Pedro', '23:00', 4);

CREATE TABLE PEDIDO_COMPRADOR (
    COMPRADOR VARCHAR(255) NOT NULL,
    PEDIDO VARCHAR(255) NOT NULL,
    CONSTRAINT  fk_comprador
    FOREIGN KEY (COMPRADOR) REFERENCES COMPRADOR (ID),
    CONSTRAINT fk_pedido
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(ID),
    PRIMARY KEY (COMPRADOR, PEDIDO));
    
    CREATE TABLE PEDIDO_ITEM (
    COMPRADOR VARCHAR(255) NOT NULL,
    PEDIDO VARCHAR(255) NOT NULL,
    CONSTRAINT  fk_comprador
    FOREIGN KEY (ITEM) REFERENCES ITEM (ID),
    CONSTRAINT fk_pedido
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(ID),
    PRIMARY KEY (ITEM, PEDIDO));
    
    CREATE TABLE COMPRADOR_ENDERECO (
    COMPRADOR VARCHAR(255) NOT NULL,
    PEDIDO VARCHAR(255) NOT NULL,
    CONSTRAINT  fk_comprador
    FOREIGN KEY (ITEM) REFERENCES ITEM (ID),
    CONSTRAINT fk_pedido
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(ID),
    PRIMARY KEY (ITEM, PEDIDO));
    
    CREATE TABLE ENDERECO_CIDADE (
    COMPRADOR VARCHAR(255) NOT NULL,
    PEDIDO VARCHAR(255) NOT NULL,
    CONSTRAINT  fk_comprador
    FOREIGN KEY (ITEM) REFERENCES ITEM (ID),
    CONSTRAINT fk_pedido
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(ID),
    PRIMARY KEY (ITEM, PEDIDO));
    
    CREATE TABLE CIDADE_ESTADO (
    COMPRADOR VARCHAR(255) NOT NULL,
    PEDIDO VARCHAR(255) NOT NULL,
    CONSTRAINT  fk_comprador
    FOREIGN KEY (ITEM) REFERENCES ITEM (ID),
    CONSTRAINT fk_pedido
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(ID),
    PRIMARY KEY (ITEM, PEDIDO));
    
    
CREATE TABLE ITEM (ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255),
    VALOR VARCHAR(255));
    
CREATE TABLE ESTADO (ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL);
    
CREATE TABLE CIDADE (ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL);
    
CREATE TABLE ENDERECO (ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
	CEP INT NOT NULL,
    CIDADE VARCHAR(255));
    